__title__ = "atlasplots"
__description__ = "ATLAS Plots for Humans"
__url__ = "TODO"
__version__ = "0.0.1"
__author__ = "Joey Carter"
__author_email__ = "joey.carter@cern.ch"
__license__ = "MIT"
__copyright__ = "Copyright (c) 2020 Joey Carter"
